<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net481</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(LibVersion)' != ''">
    <DefineConstants>$(DefineConstants);LibVersion;LibVersion_$(LibVersion.Replace('.', '_'))</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\SharpSRTP\PolyfillExtensions.cs" Link="PolyfillExtensions.cs" />
    <Compile Include="..\SharpSRTP.Tests\TestPolyfillExtensions.cs" Link="TestPolyfillExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpSRTP\SharpSRTP.csproj" Condition="'$(LibVersion)' == ''" />
    <PackageReference Include="SharpSRTP" Version="$(LibVersion)" Condition="'$(LibVersion)' != ''" />
  </ItemGroup>

</Project>
