// SharpSRTP
// Copyright (C) 2025 Lukas Volf
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
// SOFTWARE.

using SharpSRTP.DTLSSRTP;
using System;
using System.Collections.Generic;

namespace SharpSRTP.Tests
{
    /// <summary>
    /// RFC8723 https://www.ietf.org/rfc/rfc8723.html
    /// </summary>
    [TestClass]
    public class TestRFC8723
    {
        public static IEnumerable<object[]> Test_Srtp_Protect_Unprotect_TestData()
        {
            var dtlsSrtpProfile = ExtendedSrtpProtectionProfile.DOUBLE_AEAD_AES_128_GCM_AEAD_AES_128_GCM;
            var masterKeySalt = "f7d54b1f77018d00a48438d4be6d1b59be683885ec77dde0d18a1e1e566044aa00fb3c11179f6a224763350e26634b952e00d0e34f6ef57b41aecbc8216832bbf18389d0f58f861065f337b8ffdb115c585cfef1019b19d71579a1792d0a6ac7467efa2e39ec36a4a75c1ff9c1f599e2";
            var rtp = "80e1000103cb6bc84218a6a3001006c801123318f6882d06086141a9c44dfbfb7e9f1cf997eb257b77c732bcf779ae750b6493aff001815dcfc814a4fb96089153b0becc4e091f2632584ee88fc01701a0dc5111f3d7b201b0a5496972275d00e503d921370ecbdebc5ac4e54572e59ca65c29ce246b438659df04633d5d0452da1b9ce729670a616b4f5050df2c7de897ca16f5762d6df93da0134d6c3d2fedb178be2fbbfa3c702673c231d5af4f1c9b2fa791a19ef3a23aee2325dc633f19ebde33f0eeec8351cfa62bbbf9339d6b7e322ba3bb5e1d31a3956475cf450984d4a274d2583d1b80e0";
            var expectedSrtp = "80e1000103cb6bc84218a6a341c2f1daae18bf8e657088e360e382cbbfd74b34c90987d06e28d3f693221b99d1f22c8cd50c01d74fe473e95a71cf65505fc05c7384a6f522835a5c7f21a3ce9a24d0293bb06f3f5b2b7e9cfa151f0ae5caef93f074d70d3eaf54d2c09f0309b1e751523f15a2c621fa182a8cb23d68edb35acee7d7ec6d142486c0a0c464118c2bd56cee57847703bcea3904a0da3e6cf240f7e295250d721977fb56005d3ec36d917055853f1cc98b3cd0e3a9b0c5e24f88533df6f238516c248815b1308c23dc72cf9c07f0db436968b57d51ece116e6d832ad85f8e3c1a962554fe90c2982f3b462a10f61f5503651bc6cd26d51ffc86cc3b101bf28991e8dd34968";

            yield return [dtlsSrtpProfile, masterKeySalt, rtp, expectedSrtp, true];
            yield return [dtlsSrtpProfile, masterKeySalt, rtp, expectedSrtp, false];
        }

        // These test vectors were generated by SharpSRTP, they are not official and can be wrong!
        [DynamicData(nameof(Test_Srtp_Protect_Unprotect_TestData))]
        [TestMethod]
        public void Test_Srtp_Protect_Unprotect(int dtlsSrtpProfile, string masterKeySalt, string rtp, string expectedSrtp, bool useSharedBuffer)
        {
            var masterKeySaltBytes = System.Convert.FromBase64String(masterKeySalt);
            var rtpBytes = Convert.FromHexString(rtp);

            var keys = DtlsSrtpProtocol.CreateMasterKeys(dtlsSrtpProfile, null, masterKeySaltBytes);

            var context = DtlsSrtpProtocol.CreateSrtpClientSessionContext(keys);

            Span<byte> srtpProtectedBytes;

            {
                srtpProtectedBytes = new byte[context.CalculateRequiredSrtpPayloadLength(rtpBytes.Length)];
                ReadOnlySpan<byte> srtpUnprotectedBytes;

                if (useSharedBuffer)
                {
                    srtpUnprotectedBytes = srtpProtectedBytes.Slice(0, rtpBytes.Length);
                    rtpBytes.AsSpan(0, rtpBytes.Length).CopyTo(srtpProtectedBytes);
                }
                else
                {
                    srtpUnprotectedBytes = rtpBytes;
                }

                var len = context.ProtectRtp(srtpProtectedBytes, srtpUnprotectedBytes);

                var expectedBytes = Convert.FromHexString(expectedSrtp);
                var actualBytes = srtpProtectedBytes.Slice(0, len).ToArray();
                Assert.IsTrue(expectedBytes.SequenceEqual(actualBytes),
                    $"ProtectRtp output does not match the expected value.\nExpected: {BitConverter.ToString(expectedBytes).Replace("-", "").ToLowerInvariant()}\nActual:   {BitConverter.ToString(actualBytes).Replace("-", "").ToLowerInvariant()}");
            }

            var decodeContext = DtlsSrtpProtocol.CreateSrtpServerSessionContext(keys);

            {
                Span<byte> srtpUnprotectedBytes;

                if (useSharedBuffer)
                {
                    srtpUnprotectedBytes = srtpProtectedBytes;
                }
                else
                {
                    srtpUnprotectedBytes = new byte[srtpProtectedBytes.Length];
                }

                var olen = decodeContext.UnprotectRtp(srtpUnprotectedBytes, srtpProtectedBytes);

                var actualUnprotected = srtpUnprotectedBytes.Slice(0, olen).ToArray();
                Assert.IsTrue(rtpBytes.SequenceEqual(actualUnprotected),
                    $"UnprotectRtp output does not match the expected value.\nExpected: {BitConverter.ToString(rtpBytes).Replace("-", "").ToLowerInvariant()}\nActual:   {BitConverter.ToString(actualUnprotected).Replace("-", "").ToLowerInvariant()}");
            }
        }
    }
}
